// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmlezqhlaybaenavaqjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptbGV6cWhsYXliYWVuYXZhcWp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NTA2ODcsImV4cCI6MjA1NTIyNjY4N30._Ikz4hdcLPDrIqRmti_ad80nd8Ur81GB-UUj9gJ7xIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);